export enum Category {
  IT = 'IT',
  WAREHOUSE = 'WAREHOUSE',
  CONSTRUCTION_MATERIAL = 'CONSTRUCTION_MATERIAL',
  TRAINING = 'TRAINING',
  EVENT = 'EVENT',
  CLEANING_MAINTENANCE = 'CLEANING_MAINTENANCE',
  SECURITY = 'SECURITY',
  EXTERNAL_SERVICES = 'EXTERNAL_SERVICES',
  OTHERS = 'OTHERS'
}
